from __future__ import annotations

import os
import json
import aiosqlite

DATABASE_PATH = os.getenv("DATABASE_PATH", "sparksage.db")

_db: aiosqlite.Connection | None = None


async def get_db() -> aiosqlite.Connection:
    """Return the shared database connection, creating it if needed."""
    global _db
    if _db is None:
        _db = await aiosqlite.connect(DATABASE_PATH)
        _db.row_factory = aiosqlite.Row
        await _db.execute("PRAGMA journal_mode=WAL")
        await _db.execute("PRAGMA foreign_keys=ON")
    return _db


async def init_db():
    """Create tables if they don't exist and run migrations."""
    db = await get_db()
    # base schema without FTS or guild_id-dependent triggers
    await db.executescript(
        """
        CREATE TABLE IF NOT EXISTS config (
            key   TEXT PRIMARY KEY,
            value TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS conversations (
            id         INTEGER PRIMARY KEY AUTOINCREMENT,
            channel_id TEXT    NOT NULL,
            role       TEXT    NOT NULL,
            content    TEXT    NOT NULL,
            provider   TEXT,
            category   TEXT,
            created_at TEXT    NOT NULL DEFAULT (datetime('now'))
        );
        CREATE INDEX IF NOT EXISTS idx_conv_channel ON conversations(channel_id);

        CREATE TABLE IF NOT EXISTS sessions (
            token      TEXT PRIMARY KEY,
            user_id    TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            expires_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS wizard_state (
            id           INTEGER PRIMARY KEY CHECK (id = 1),
            completed    INTEGER NOT NULL DEFAULT 0,
            current_step INTEGER NOT NULL DEFAULT 0,
            data         TEXT    NOT NULL DEFAULT '{}'
        );

        CREATE TABLE IF NOT EXISTS faqs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            guild_id TEXT NOT NULL,
            question TEXT NOT NULL,
            answer TEXT NOT NULL,
            match_keywords TEXT NOT NULL,
            times_used INTEGER DEFAULT 0,
            created_by TEXT,
            created_at TEXT DEFAULT (datetime('now'))
        );

        CREATE TABLE IF NOT EXISTS command_permissions (
            command_name TEXT NOT NULL,
            guild_id TEXT NOT NULL,
            role_id TEXT NOT NULL,
            PRIMARY KEY (command_name, guild_id, role_id)
        );

        CREATE TABLE IF NOT EXISTS guild_config (
            guild_id TEXT NOT NULL,
            key      TEXT NOT NULL,
            value    TEXT NOT NULL,
            PRIMARY KEY (guild_id, key)
        );

        CREATE TABLE IF NOT EXISTS moderation_logs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            guild_id TEXT NOT NULL,
            channel_id TEXT NOT NULL,
            user_id TEXT NOT NULL,
            message_content TEXT NOT NULL,
            reason TEXT NOT NULL,
            severity TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT (datetime('now'))
        );

        CREATE TABLE IF NOT EXISTS channel_prompts (
            channel_id TEXT PRIMARY KEY,
            guild_id TEXT NOT NULL,
            system_prompt TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS channel_providers (
            channel_id TEXT PRIMARY KEY,
            guild_id TEXT NOT NULL,
            provider TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS channel_autotranslate_settings (
            channel_id TEXT PRIMARY KEY,
            guild_id TEXT NOT NULL,
            enabled INTEGER NOT NULL DEFAULT 0,
            target_language TEXT
        );

        -- topic tags for channels (auto-generated by AI)
        CREATE TABLE IF NOT EXISTS channel_topics (
            channel_id TEXT PRIMARY KEY,
            topic TEXT
        );

        CREATE TABLE IF NOT EXISTS analytics (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            event_type  TEXT NOT NULL,
            guild_id    TEXT,
            guild_name  TEXT,
            channel_id  TEXT,
            user_id     TEXT,
            user_name   TEXT,
            provider    TEXT,
            tokens_used INTEGER,
            latency_ms  INTEGER,
            input_tokens INTEGER,
            output_tokens INTEGER,
            estimated_cost REAL,
            created_at  TEXT NOT NULL DEFAULT (datetime('now'))
        );

        CREATE TABLE IF NOT EXISTS plugins (
            name    TEXT PRIMARY KEY,
            enabled INTEGER NOT NULL DEFAULT 0
        );

        CREATE TABLE IF NOT EXISTS auto_responses (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            guild_id TEXT NOT NULL,
            keyword TEXT NOT NULL,
            response TEXT NOT NULL,
            match_type TEXT NOT NULL DEFAULT 'contains', -- 'exact' or 'contains'
            is_case_sensitive INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT (datetime('now'))
        );

        INSERT OR IGNORE INTO wizard_state (id) VALUES (1);
        """
    )
    # Migration for existing DB
    try:
        await db.execute("ALTER TABLE conversations ADD COLUMN guild_id TEXT")
    except:
        pass
    try:
        await db.execute("ALTER TABLE conversations ADD COLUMN category TEXT")
    except:
        pass

    # after migrations, ensure indices
    await db.executescript(
        """
        CREATE INDEX IF NOT EXISTS idx_conv_guild ON conversations(guild_id);
        """
    )

    # now create FTS and triggers once guild_id exists
    await db.executescript(
        """
        CREATE VIRTUAL TABLE IF NOT EXISTS conversations_fts USING fts5(
            content, channel_id, guild_id, content='conversations', content_rowid='id'
        );

        CREATE TRIGGER IF NOT EXISTS conversations_ai_after_insert
            AFTER INSERT ON conversations
            BEGIN
                INSERT INTO conversations_fts(rowid, content, channel_id, guild_id)
                VALUES (new.id, new.content, new.channel_id, new.guild_id);
            END;
        CREATE TRIGGER IF NOT EXISTS conversations_ai_after_update
            AFTER UPDATE ON conversations
            BEGIN
                INSERT INTO conversations_fts(conversations_fts, rowid, content, channel_id, guild_id)
                VALUES('delete', old.id, old.content, old.channel_id, old.guild_id);
                INSERT INTO conversations_fts(rowid, content, channel_id, guild_id)
                VALUES (new.id, new.content, new.channel_id, new.guild_id);
            END;
        CREATE TRIGGER IF NOT EXISTS conversations_ai_after_delete
            AFTER DELETE ON conversations
            BEGIN
                INSERT INTO conversations_fts(conversations_fts, rowid, content, channel_id, guild_id)
                VALUES('delete', old.id, old.content, old.channel_id, old.guild_id);
            END;
        """
    )

    # Backfill FTS with existing messages (migration for existing DBs)
    try:
        cursor = await db.execute("SELECT COUNT(*) FROM conversations_fts")
        row = await cursor.fetchone()
        fts_count = row[0] if row else 0
        
        if fts_count == 0:
            # FTS table is empty, backfill from conversations
            await db.execute(
                """INSERT INTO conversations_fts(rowid, content, channel_id, guild_id)
                   SELECT id, content, channel_id, guild_id FROM conversations"""
            )
            await db.commit()
    except Exception as e:
        pass  # FTS might not exist yet or other issues, silently skip

    # Analytics migration
    try:
        await db.execute("ALTER TABLE analytics ADD COLUMN input_tokens INTEGER")
    except:
        pass
    try:
        await db.execute("ALTER TABLE analytics ADD COLUMN output_tokens INTEGER")
    except:
        pass
    try:
        await db.execute("ALTER TABLE analytics ADD COLUMN estimated_cost REAL")
    except:
        pass
    try:
        await db.execute("ALTER TABLE analytics ADD COLUMN user_name TEXT")
    except:
        pass
    try:
        await db.execute("ALTER TABLE analytics ADD COLUMN guild_name TEXT")
    except:
        pass

    # Rebuild FTS5 index to ensure proper tokenization
    try:
        await db.execute('INSERT INTO conversations_fts(conversations_fts) VALUES("rebuild")')
    except Exception as e:
        pass  # FTS table might not exist yet

    await db.commit()


# --- Config helpers ---


async def get_config(key: str, default: str | None = None) -> str | None:
    """Get a config value from the database."""
    db = await get_db()
    cursor = await db.execute("SELECT value FROM config WHERE key = ?", (key,))
    row = await cursor.fetchone()
    return row["value"] if row else default


async def get_all_config() -> dict[str, str]:
    """Return all config key-value pairs."""
    db = await get_db()
    cursor = await db.execute("SELECT key, value FROM config")
    rows = await cursor.fetchall()
    return {row["key"]: row["value"] for row in rows}


async def set_config(key: str, value: str):
    """Set a config value in the database."""
    db = await get_db()
    await db.execute(
        "INSERT INTO config (key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value",
        (key, value),
    )
    await db.commit()


async def set_config_bulk(data: dict[str, str]):
    """Set multiple config values at once."""
    db = await get_db()
    await db.executemany(
        "INSERT INTO config (key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value",
        list(data.items()),
    )
    await db.commit()


async def sync_env_to_db():
    """Seed the DB config table from current environment / .env values."""
    import config as cfg

    env_keys = {
        "DISCORD_TOKEN": cfg.DISCORD_TOKEN or "",
        "AI_PROVIDER": cfg.AI_PROVIDER,
        "GEMINI_API_KEY": cfg.GEMINI_API_KEY or "",
        "GEMINI_MODEL": cfg.GEMINI_MODEL,
        "GROQ_API_KEY": cfg.GROQ_API_KEY or "",
        "GROQ_MODEL": cfg.GROQ_MODEL,
        "OPENROUTER_API_KEY": cfg.OPENROUTER_API_KEY or "",
        "OPENROUTER_MODEL": cfg.OPENROUTER_MODEL,
        "ANTHROPIC_API_KEY": cfg.ANTHROPIC_API_KEY or "",
        "ANTHROPIC_MODEL": cfg.ANTHROPIC_MODEL,
        "OPENAI_API_KEY": cfg.OPENAI_API_KEY or "",
        "OPENAI_MODEL": cfg.OPENAI_MODEL,
        "BOT_PREFIX": cfg.BOT_PREFIX,
        "MAX_TOKENS": str(cfg.MAX_TOKENS),
        "SYSTEM_PROMPT": cfg.SYSTEM_PROMPT,
        "WELCOME_ENABLED": "true" if cfg.WELCOME_ENABLED else "false",
        "WELCOME_DM_ENABLED": "true" if cfg.WELCOME_DM_ENABLED else "false",
        "WELCOME_CHANNEL_ID": cfg.WELCOME_CHANNEL_ID,
        "WELCOME_MESSAGE": cfg.WELCOME_MESSAGE,
        "WELCOME_RULES": cfg.WELCOME_RULES,
        "WELCOME_LINKS": cfg.WELCOME_LINKS,
        "DIGEST_ENABLED": "true" if cfg.DIGEST_ENABLED else "false",
        "DIGEST_CHANNEL_ID": cfg.DIGEST_CHANNEL_ID,
        "DIGEST_TIME": cfg.DIGEST_TIME,
        "MODERATION_ENABLED": "true" if cfg.MODERATION_ENABLED else "false",
        "MOD_LOG_CHANNEL_ID": cfg.MOD_LOG_CHANNEL_ID,
        "MODERATION_SENSITIVITY": cfg.MODERATION_SENSITIVITY,
        "TRANSLATE_ENABLED": "true" if cfg.TRANSLATE_ENABLED else "false",
        "RATE_LIMIT_USER": str(cfg.RATE_LIMIT_USER),
        "RATE_LIMIT_GUILD": str(cfg.RATE_LIMIT_GUILD),
        "DISABLED_PROVIDERS": cfg.DISABLED_PROVIDERS,
        "ADMIN_PASSWORD": cfg.ADMIN_PASSWORD,
        "DISCORD_CLIENT_ID": cfg.DISCORD_CLIENT_ID,
        "DISCORD_CLIENT_SECRET": cfg.DISCORD_CLIENT_SECRET,
        "JWT_SECRET": cfg.JWT_SECRET,
    }
    # Only insert keys that don't already exist in DB (don't overwrite user edits)
    db = await get_db()
    for key, value in env_keys.items():
        await db.execute(
            "INSERT OR IGNORE INTO config (key, value) VALUES (?, ?)",
            (key, value),
        )
    await db.commit()


async def sync_db_to_env():
    """Write DB config back to the .env file."""
    from dotenv import dotenv_values, set_key

    env_path = os.path.join(os.path.dirname(__file__), ".env")
    all_config = await get_all_config()

    for key, value in all_config.items():
        set_key(env_path, key, value)


# --- Conversation helpers ---


async def add_message(channel_id: str, role: str, content: str, provider: str | None = None, category: str | None = None, guild_id: str | None = None):
    """Add a message to conversation history."""
    db = await get_db()
    await db.execute(
        "INSERT INTO conversations (channel_id, guild_id, role, content, provider, category) VALUES (?, ?, ?, ?, ?, ?)",
        (channel_id, guild_id, role, content, provider, category),
    )
    await db.commit()


async def get_messages(channel_id: str, limit: int = 20) -> list[dict]:
    """Get recent messages for a channel."""
    db = await get_db()
    cursor = await db.execute(
        "SELECT role, content, provider, category, created_at FROM conversations WHERE channel_id = ? ORDER BY id DESC LIMIT ?",
        (channel_id, limit),
    )
    rows = await cursor.fetchall()
    return [dict(row) for row in reversed(rows)]


async def clear_messages(channel_id: str):
    """Delete all messages for a channel."""
    db = await get_db()
    await db.execute("DELETE FROM conversations WHERE channel_id = ?", (channel_id,))
    await db.commit()


async def list_channels(guild_id: str | None = None) -> list[dict]:
    """List all channels with message counts and code review status."""
    db = await get_db()
    
    query = """
        SELECT 
            channel_id, 
            guild_id,
            COUNT(*) as message_count, 
            MAX(created_at) as last_active,
            MAX(CASE WHEN category = 'code_review' THEN 1 ELSE 0 END) as has_code_review
        FROM conversations
    """
    params = []
    
    if guild_id:
        query += " WHERE guild_id = ?"
        params.append(guild_id)
        
    query += """
        GROUP BY channel_id, guild_id
        ORDER BY last_active DESC
    """
    
    cursor = await db.execute(query, params)
    rows = await cursor.fetchall()
    return [dict(row) for row in rows]


# --- Search & topic helpers ---

async def search_messages(query: str, guild_id: str | None = None, limit: int = 100) -> list[dict]:
    """Search conversation content using FTS5. Returns matching message rows."""
    db = await get_db()
    # Prepare query for FTS5: escape double quotes and enclose in double quotes for literal matching
    # This prevents FTS5 from interpreting special characters like '?' as syntax errors.
    prepared_query = '"' + query.replace('"', '""') + '"'

    if guild_id:
        cursor = await db.execute(
            "SELECT channel_id, role, content, provider, category, created_at "
            "FROM conversations "
            "WHERE guild_id = ? AND id IN (SELECT rowid FROM conversations_fts WHERE conversations_fts MATCH ?) "
            "ORDER BY created_at DESC LIMIT ?",
            (guild_id, prepared_query, limit),
        )
    else:
        cursor = await db.execute(
            "SELECT channel_id, role, content, provider, category, created_at "
            "FROM conversations "
            "WHERE id IN (SELECT rowid FROM conversations_fts WHERE conversations_fts MATCH ?) "
            "ORDER BY created_at DESC LIMIT ?",
            (prepared_query, limit),
        )
    rows = await cursor.fetchall()
    return [dict(row) for row in rows]


async def set_channel_topic(channel_id: str, topic: str):
    """Store a topic tag for a channel."""
    db = await get_db()
    await db.execute(
        "INSERT INTO channel_topics (channel_id, topic) VALUES (?, ?) "
        "ON CONFLICT(channel_id) DO UPDATE SET topic = excluded.topic",
        (channel_id, topic),
    )
    await db.commit()


async def get_channel_topic(channel_id: str) -> str | None:
    """Retrieve the topic tag for a channel, if any."""
    db = await get_db()
    cursor = await db.execute(
        "SELECT topic FROM channel_topics WHERE channel_id = ?",
        (channel_id,),
    )
    row = await cursor.fetchone()
    return row["topic"] if row else None


# --- Wizard helpers ---


async def get_wizard_state() -> dict:
    """Get the wizard state."""
    db = await get_db()
    cursor = await db.execute("SELECT completed, current_step, data FROM wizard_state WHERE id = 1")
    row = await cursor.fetchone()
    return {
        "completed": bool(row["completed"]),
        "current_step": row["current_step"],
        "data": json.loads(row["data"]),
    }


async def set_wizard_state(completed: bool | None = None, current_step: int | None = None, data: dict | None = None):
    """Update wizard state fields."""
    db = await get_db()
    updates = []
    params = []
    if completed is not None:
        updates.append("completed = ?")
        params.append(int(completed))
    if current_step is not None:
        updates.append("current_step = ?")
        params.append(current_step)
    if data is not None:
        updates.append("data = ?")
        params.append(json.dumps(data))
    if updates:
        await db.execute(f"UPDATE wizard_state SET {', '.join(updates)} WHERE id = 1", params)
        await db.commit()


# --- Session helpers ---


async def create_session(token: str, user_id: str, expires_at: str):
    """Store a session token."""
    db = await get_db()
    await db.execute(
        "INSERT INTO sessions (token, user_id, expires_at) VALUES (?, ?, ?)",
        (token, user_id, expires_at),
    )
    await db.commit()


async def validate_session(token: str) -> dict | None:
    """Validate a session token, return session data or None."""
    db = await get_db()
    cursor = await db.execute(
        "SELECT user_id, expires_at FROM sessions WHERE token = ? AND expires_at > datetime('now')",
        (token,),
    )
    row = await cursor.fetchone()
    return dict(row) if row else None


async def delete_session(token: str):
    """Delete a session."""
    db = await get_db()
    await db.execute("DELETE FROM sessions WHERE token = ?", (token,))
    await db.commit()


async def close_db():
    """Close the database connection."""
    global _db
    if _db:
        await _db.close()
        _db = None


# --- FAQ helpers ---


async def add_faq(guild_id: str, question: str, answer: str, keywords: str, created_by: str | None = None):
    """Add a new FAQ entry."""
    db = await get_db()
    await db.execute(
        "INSERT INTO faqs (guild_id, question, answer, match_keywords, created_by) VALUES (?, ?, ?, ?, ?)",
        (guild_id, question, answer, keywords, created_by),
    )
    await db.commit()


async def list_faqs(guild_id: str | None = None) -> list[dict]:
    """List all FAQs, optionally filtered by guild."""
    db = await get_db()
    if guild_id:
        cursor = await db.execute("SELECT * FROM faqs WHERE guild_id = ? ORDER BY id DESC", (guild_id,))
    else:
        cursor = await db.execute("SELECT * FROM faqs ORDER BY id DESC")
    rows = await cursor.fetchall()
    return [dict(row) for row in rows]


async def delete_faq(faq_id: int, guild_id: str | None = None):
    """Delete an FAQ entry."""
    db = await get_db()
    if guild_id:
        await db.execute("DELETE FROM faqs WHERE id = ? AND guild_id = ?", (faq_id, guild_id))
    else:
        await db.execute("DELETE FROM faqs WHERE id = ?", (faq_id,))
    await db.commit()


async def increment_faq_usage(faq_id: int):
    """Increment the usage counter for an FAQ."""
    db = await get_db()
    await db.execute("UPDATE faqs SET times_used = times_used + 1 WHERE id = ?", (faq_id,))
    await db.commit()


# --- Permission helpers ---


async def set_command_permission(command_name: str, guild_id: str, role_id: str):
    """Restrict a command to a specific role in a guild."""
    db = await get_db()
    await db.execute(
        "INSERT OR IGNORE INTO command_permissions (command_name, guild_id, role_id) VALUES (?, ?, ?)",
        (command_name, guild_id, role_id),
    )
    await db.commit()


async def remove_command_permission(command_name: str, guild_id: str, role_id: str):
    """Remove a role restriction for a command."""
    db = await get_db()
    await db.execute(
        "DELETE FROM command_permissions WHERE command_name = ? AND guild_id = ? AND role_id = ?",
        (command_name, guild_id, role_id),
    )
    await db.commit()


async def list_command_permissions(guild_id: str | None = None) -> list[dict]:
    """List all command permissions, optionally filtered by guild."""
    db = await get_db()
    if guild_id:
        cursor = await db.execute("SELECT * FROM command_permissions WHERE guild_id = ?", (guild_id,))
    else:
        cursor = await db.execute("SELECT * FROM command_permissions")
    rows = await cursor.fetchall()
    return [dict(row) for row in rows]


async def get_allowed_roles(command_name: str, guild_id: str) -> list[str]:
    """Get list of role IDs allowed to use a command in a guild."""
    db = await get_db()
    cursor = await db.execute(
        "SELECT role_id FROM command_permissions WHERE command_name = ? AND guild_id = ?",
        (command_name, guild_id),
    )
    rows = await cursor.fetchall()
    return [row["role_id"] for row in rows]


# --- Guild Config helpers ---


async def get_guild_config(guild_id: str, key: str, default: str | None = None) -> str | None:
    """Get a per-guild config value."""
    db = await get_db()
    cursor = await db.execute(
        "SELECT value FROM guild_config WHERE guild_id = ? AND key = ?",
        (guild_id, key),
    )
    row = await cursor.fetchone()
    return row["value"] if row else default


async def get_all_guild_config(guild_id: str) -> dict[str, str]:
    """Get all config for a specific guild."""
    db = await get_db()
    cursor = await db.execute("SELECT key, value FROM guild_config WHERE guild_id = ?", (guild_id,))
    rows = await cursor.fetchall()
    return {row["key"]: row["value"] for row in rows}


async def set_guild_config(guild_id: str, key: str, value: str):
    """Set a per-guild config value."""
    db = await get_db()
    await db.execute(
        "INSERT INTO guild_config (guild_id, key, value) VALUES (?, ?, ?) ON CONFLICT(guild_id, key) DO UPDATE SET value = excluded.value",
        (guild_id, key, value),
    )
    await db.commit()


async def set_guild_config_bulk(guild_id: str, data: dict[str, str]):
    """Set multiple per-guild config values."""
    db = await get_db()
    await db.executemany(
        "INSERT INTO guild_config (guild_id, key, value) VALUES (?, ?, ?) ON CONFLICT(guild_id, key) DO UPDATE SET value = excluded.value",
        [(guild_id, k, v) for k, v in data.items()],
    )
    await db.commit()


async def get_usage_stats() -> dict:
    """Get message usage statistics for charts."""
    db = await get_db()
    
    # Message count by day (last 7 days)
    cursor = await db.execute(
        """
        SELECT date(created_at) as day, COUNT(*) as count
        FROM conversations
        WHERE created_at > datetime('now', '-7 days')
        GROUP BY day
        ORDER BY day ASC
        """
    )
    daily_rows = await cursor.fetchall()
    daily_messages = [{"day": row["day"], "count": row["count"]} for row in daily_rows]
    
    # Provider distribution
    cursor = await db.execute(
        """
        SELECT provider, COUNT(*) as count
        FROM conversations
        WHERE provider IS NOT NULL
        GROUP BY provider
        ORDER BY count DESC
        """
    )
    provider_rows = await cursor.fetchall()
    provider_distribution = [{"name": row["provider"], "value": row["count"]} for row in provider_rows]
    
    # Total stats
    cursor = await db.execute("SELECT COUNT(*) as count FROM conversations")
    total_messages = (await cursor.fetchone())["count"]
    
    cursor = await db.execute("SELECT COUNT(DISTINCT channel_id) as count FROM conversations WHERE channel_id IS NOT NULL AND channel_id != ''")
    total_channels = (await cursor.fetchone())["count"]

    total_guilds = await get_total_guilds()

    return {
        "daily_messages": daily_messages,
        "provider_distribution": provider_distribution,
        "total_messages": total_messages,
        "total_channels": total_channels,
        "total_guilds": total_guilds
    }


async def log_moderation_event(guild_id: str, channel_id: str, user_id: str, content: str, reason: str, severity: str):
    """Log a moderation event to the database."""
    db = await get_db()
    await db.execute(
        "INSERT INTO moderation_logs (guild_id, channel_id, user_id, message_content, reason, severity) VALUES (?, ?, ?, ?, ?, ?)",
        (guild_id, channel_id, user_id, content, reason, severity),
    )
    await db.commit()


async def get_moderation_stats(guild_id: str | None = None) -> dict:
    """Get moderation statistics."""
    db = await get_db()
    if guild_id:
        cursor = await db.execute("SELECT COUNT(*) as count FROM moderation_logs WHERE guild_id = ?", (guild_id,))
    else:
        cursor = await db.execute("SELECT COUNT(*) as count FROM moderation_logs")
    total_flagged = (await cursor.fetchone())["count"]
    
    # Severity distribution
    query = "SELECT severity, COUNT(*) as count FROM moderation_logs"
    params = []
    if guild_id:
        query += " WHERE guild_id = ?"
        params.append(guild_id)
    query += " GROUP BY severity"
    
    cursor = await db.execute(query, params)
    rows = await cursor.fetchall()
    severity_dist = {row["severity"]: row["count"] for row in rows}
    
    return {
        "total_flagged": total_flagged,
        "severity_distribution": severity_dist
    }


async def get_total_guilds() -> int:
    """Count unique guild IDs across faqs, command_permissions, and guild_config."""
    db = await get_db()
    
    # We use a set of subqueries and UNION to get all unique guild IDs
    query = """
    SELECT COUNT(DISTINCT guild_id) as count FROM (
        SELECT guild_id FROM faqs WHERE guild_id != '1'
        UNION
        SELECT guild_id FROM command_permissions
        UNION
        SELECT guild_id FROM guild_config
    )
    """
    cursor = await db.execute(query)
    row = await cursor.fetchone()
    return row["count"] if row else 0


async def get_channel_prompt(channel_id: str) -> str | None:
    """Get a channel-specific system prompt."""
    db = await get_db()
    cursor = await db.execute("SELECT system_prompt FROM channel_prompts WHERE channel_id = ?", (channel_id,))
    row = await cursor.fetchone()
    return row["system_prompt"] if row else None


async def set_channel_prompt(channel_id: str, guild_id: str, system_prompt: str):
    """Set a channel-specific system prompt."""
    db = await get_db()
    await db.execute(
        "INSERT INTO channel_prompts (channel_id, guild_id, system_prompt) VALUES (?, ?, ?) ON CONFLICT(channel_id) DO UPDATE SET system_prompt = excluded.system_prompt",
        (channel_id, guild_id, system_prompt),
    )
    await db.commit()


async def delete_channel_prompt(channel_id: str):
    """Delete a channel-specific system prompt."""
    db = await get_db()
    await db.execute("DELETE FROM channel_prompts WHERE channel_id = ?", (channel_id,))
    await db.commit()


async def list_channel_prompts(guild_id: str | None = None) -> list[dict]:
    """List all channel-specific prompts, optionally filtered by guild."""
    db = await get_db()
    if guild_id:
        cursor = await db.execute("SELECT * FROM channel_prompts WHERE guild_id = ?", (guild_id,))
    else:
        cursor = await db.execute("SELECT * FROM channel_prompts")
    rows = await cursor.fetchall()
    return [dict(row) for row in rows]


async def get_channel_provider(channel_id: str) -> str | None:
    """Get a channel-specific AI provider."""
    db = await get_db()
    cursor = await db.execute("SELECT provider FROM channel_providers WHERE channel_id = ?", (channel_id,))
    row = await cursor.fetchone()
    return row["provider"] if row else None


async def set_channel_provider(channel_id: str, guild_id: str, provider: str):
    """Set a channel-specific AI provider."""
    db = await get_db()
    await db.execute(
        "INSERT INTO channel_providers (channel_id, guild_id, provider) VALUES (?, ?, ?) ON CONFLICT(channel_id) DO UPDATE SET provider = excluded.provider",
        (channel_id, guild_id, provider),
    )
    await db.commit()


async def delete_channel_provider(channel_id: str):
    """Delete a channel-specific AI provider."""
    db = await get_db()
    await db.execute("DELETE FROM channel_providers WHERE channel_id = ?", (channel_id,))
    await db.commit()


async def list_channel_providers(guild_id: str | None = None) -> list[dict]:
    """List all channel-specific providers, optionally filtered by guild."""
    db = await get_db()
    if guild_id:
        cursor = await db.execute("SELECT * FROM channel_providers WHERE guild_id = ?", (guild_id,))
    else:
        cursor = await db.execute("SELECT * FROM channel_providers")
    rows = await cursor.fetchall()
    return [dict(row) for row in rows]


# --- Channel Auto-translate helpers ---


async def get_channel_autotranslate_setting(channel_id: str) -> tuple[str, bool, str | None] | None:
    """Get a channel-specific auto-translate setting."""
    db = await get_db()
    cursor = await db.execute("SELECT guild_id, enabled, target_language FROM channel_autotranslate_settings WHERE channel_id = ?", (channel_id,))
    row = await cursor.fetchone()
    if row:
        return row["guild_id"], bool(row["enabled"]), row["target_language"]
    return None


async def set_channel_autotranslate_setting(channel_id: str, guild_id: str, enabled: bool, target_language: str | None = None):
    """Set a channel-specific auto-translate setting."""
    db = await get_db()
    await db.execute(
        "INSERT INTO channel_autotranslate_settings (channel_id, guild_id, enabled, target_language) VALUES (?, ?, ?, ?) ON CONFLICT(channel_id) DO UPDATE SET enabled = excluded.enabled, target_language = excluded.target_language",
        (channel_id, guild_id, int(enabled), target_language),
    )
    await db.commit()


async def delete_channel_autotranslate_setting(channel_id: str):
    """Delete a channel-specific auto-translate setting."""
    db = await get_db()
    await db.execute("DELETE FROM channel_autotranslate_settings WHERE channel_id = ?", (channel_id,))
    await db.commit()


# --- Analytics helpers ---


async def log_analytics(
    event_type: str,
    guild_id: str | None = None,
    guild_name: str | None = None,
    channel_id: str | None = None,
    user_id: str | None = None,
    user_name: str | None = None,
    provider: str | None = None,
    tokens_used: int | None = None,
    latency_ms: int | None = None,
    input_tokens: int | None = None,
    output_tokens: int | None = None,
    estimated_cost: float | None = None,
):
    """Record an event in the analytics table."""
    db = await get_db()
    await db.execute(
        """
        INSERT INTO analytics (event_type, guild_id, guild_name, channel_id, user_id, user_name, provider, tokens_used, latency_ms, input_tokens, output_tokens, estimated_cost)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (event_type, guild_id, guild_name, channel_id, user_id, user_name, provider, tokens_used, latency_ms, input_tokens, output_tokens, estimated_cost),
    )
    await db.commit()


async def get_analytics_summary(days: int = 7, guild_id: str | None = None) -> dict:
    """Get summarized analytics for dashboard charts."""
    db = await get_db()
    
    # Events per day
    query_events = """
        SELECT date(created_at) as day, COUNT(*) as count
        FROM analytics
        WHERE created_at > datetime('now', ?)
    """
    params_events = [f"-{days} days"]
    if guild_id:
        query_events += " AND guild_id = ?"
        params_events.append(guild_id)
    query_events += " GROUP BY day ORDER BY day ASC"
    
    cursor = await db.execute(query_events, params_events)
    daily_events = [{"day": r["day"], "count": r["count"]} for r in await cursor.fetchall()]
    
    # Provider distribution
    query_prov = """
        SELECT provider, COUNT(*) as count
        FROM analytics
        WHERE provider IS NOT NULL
    """
    params_prov = []
    if guild_id:
        query_prov += " AND guild_id = ?"
        params_prov.append(guild_id)
    query_prov += " GROUP BY provider"
    
    cursor = await db.execute(query_prov, params_prov)
    provider_dist = [{"name": r["provider"], "value": r["count"]} for r in await cursor.fetchall()]
    
    # Top channels
    query_chan = """
        SELECT channel_id, COUNT(*) as count
        FROM analytics
        WHERE channel_id IS NOT NULL
    """
    params_chan = []
    if guild_id:
        query_chan += " AND guild_id = ?"
        params_chan.append(guild_id)
    query_chan += " GROUP BY channel_id ORDER BY count DESC LIMIT 5"
    
    cursor = await db.execute(query_chan, params_chan)
    top_channels = [{"id": r["channel_id"], "count": r["count"]} for r in await cursor.fetchall()]
    
    # Average latency
    query_lat = """
        SELECT date(created_at) as day, AVG(latency_ms) as avg_latency
        FROM analytics
        WHERE latency_ms IS NOT NULL AND created_at > datetime('now', ?)
    """
    params_lat = [f"-{days} days"]
    if guild_id:
        query_lat += " AND guild_id = ?"
        params_lat.append(guild_id)
    query_lat += " GROUP BY day ORDER BY day ASC"
    
    cursor = await db.execute(query_lat, params_lat)
    latency_history = [{"day": r["day"], "latency": round(r["avg_latency"] or 0)} for r in await cursor.fetchall()]

    # Rate limited count
    query_rate = "SELECT COUNT(*) as count FROM analytics WHERE event_type = 'rate_limited' AND created_at > datetime('now', ?)"
    params_rate = [f"-{days} days"]
    if guild_id:
        query_rate += " AND guild_id = ?"
        params_rate.append(guild_id)
        
    cursor = await db.execute(query_rate, params_rate)
    total_rate_limited = (await cursor.fetchone())["count"]

    # Cost metrics
    query_cost = """
        SELECT provider, SUM(estimated_cost) as cost
        FROM analytics
        WHERE estimated_cost IS NOT NULL AND created_at > datetime('now', ?)
    """
    params_cost = [f"-{days} days"]
    if guild_id:
        query_cost += " AND guild_id = ?"
        params_cost.append(guild_id)
    query_cost += " GROUP BY provider"
    
    cursor = await db.execute(query_cost, params_cost)
    cost_by_provider = {r["provider"]: r["cost"] for r in await cursor.fetchall()}
    
    total_cost = sum(cost_by_provider.values())

    return {
        "daily_events": daily_events,
        "provider_distribution": provider_dist,
        "top_channels": top_channels,
        "latency_history": latency_history,
        "total_rate_limited": total_rate_limited,
        "cost_by_provider": cost_by_provider,
        "total_cost": total_cost
    }


# --- Plugin helpers ---


async def set_plugin_enabled(name: str, enabled: bool):
    """Set whether a plugin is enabled."""
    db = await get_db()
    await db.execute(
        "INSERT INTO plugins (name, enabled) VALUES (?, ?) ON CONFLICT(name) DO UPDATE SET value = excluded.enabled",
        (name, int(enabled)),
    )
    await db.commit()


async def delete_plugin_state(name: str):
    """Remove a plugin from the database."""
    db = await get_db()
    await db.execute("DELETE FROM plugins WHERE name = ?", (name,))
    await db.commit()



async def get_enabled_plugins() -> list[str]:
    """Return a list of all enabled plugin names."""
    db = await get_db()
    cursor = await db.execute("SELECT name FROM plugins WHERE enabled = 1")
    rows = await cursor.fetchall()
    return [r["name"] for r in rows]


async def get_plugin_states() -> dict[str, bool]:
    """Return a map of plugin names to their enabled state."""
    db = await get_db()
    cursor = await db.execute("SELECT name, enabled FROM plugins")
    rows = await cursor.fetchall()
    return {r["name"]: bool(r["enabled"]) for r in rows}


# --- Auto-responder helpers ---


async def add_auto_response(guild_id: str, keyword: str, response: str, match_type: str = "contains", is_case_sensitive: bool = False):
    """Add a new auto-response."""
    db = await get_db()
    await db.execute(
        "INSERT INTO auto_responses (guild_id, keyword, response, match_type, is_case_sensitive) VALUES (?, ?, ?, ?, ?)",
        (guild_id, keyword, response, match_type, int(is_case_sensitive)),
    )
    await db.commit()


async def list_auto_responses(guild_id: str | None = None) -> list[dict]:
    """List auto-responses, optionally filtered by guild."""
    db = await get_db()
    if guild_id:
        cursor = await db.execute("SELECT * FROM auto_responses WHERE guild_id = ? ORDER BY id DESC", (guild_id,))
    else:
        cursor = await db.execute("SELECT * FROM auto_responses ORDER BY id DESC")
    rows = await cursor.fetchall()
    return [dict(row) for row in rows]


async def update_auto_response(response_id: int, keyword: str, response: str, match_type: str, is_case_sensitive: bool, guild_id: str | None = None):
    """Update an auto-response."""
    db = await get_db()
    query = "UPDATE auto_responses SET keyword = ?, response = ?, match_type = ?, is_case_sensitive = ? WHERE id = ?"
    params = [keyword, response, match_type, int(is_case_sensitive), response_id]
    
    if guild_id:
        query += " AND guild_id = ?"
        params.append(guild_id)
        
    await db.execute(query, params)
    await db.commit()


async def delete_auto_response(response_id: int, guild_id: str | None = None):
    """Delete an auto-response."""
    db = await get_db()
    if guild_id:
        await db.execute("DELETE FROM auto_responses WHERE id = ? AND guild_id = ?", (response_id, guild_id))
    else:
        await db.execute("DELETE FROM auto_responses WHERE id = ?", (response_id,))
    await db.commit()


async def get_rate_limit_stats(limit: int = 10) -> dict:
    """Get rate limiting statistics from analytics."""
    db = await get_db()
    
    # Per-user usage (last 24h)
    cursor = await db.execute(
        """
        SELECT user_id, user_name, COUNT(*) as count
        FROM analytics
        WHERE user_id IS NOT NULL AND event_type NOT IN ('rate_limited', 'moderation_check')
        AND created_at > datetime('now', '-1 day')
        GROUP BY user_id
        ORDER BY count DESC
        LIMIT ?
        """,
        (limit,)
    )
    user_usage = [{"user_id": r["user_id"], "user_name": r["user_name"], "count": r["count"]} for r in await cursor.fetchall()]
    
    # Per-guild usage (last 24h)
    cursor = await db.execute(
        """
        SELECT guild_id, guild_name, COUNT(*) as count
        FROM analytics
        WHERE guild_id IS NOT NULL AND event_type NOT IN ('rate_limited', 'moderation_check')
        AND created_at > datetime('now', '-1 day')
        GROUP BY guild_id
        ORDER BY count DESC
        LIMIT ?
        """,
        (limit,)
    )
    guild_usage = [{"guild_id": r["guild_id"], "guild_name": r["guild_name"], "count": r["count"]} for r in await cursor.fetchall()]
    
    return {
        "user_usage": user_usage,
        "guild_usage": guild_usage
    }
